import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 자동 사이드바 생성 - docs 디렉토리의 파일들을 자동으로 감지하여 사이드바 구성
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'utils', // docs 디렉토리 내의 모든 파일을 자동으로 포함
    },
  ],
  
  // 알고리즘 사이드바
  algorithmSidebar: [
    {
      type: 'autogenerated',
      dirName: 'algorithm', // docs/algorithm 디렉토리의 파일들을 자동으로 포함
    },
  ],
};

export default sidebars;
